theme: minima

title: Yiyi's Pages
description: Natural Language Processing, Machine Learning, Deep Learning, Time Series Analysis
url: "https://siebeniris.github.io"
email: chen.yiyi@pm.me
twitter_username: YiyiChen


# build settings
markdown: kramdown

permalink: /:category

plugins:
    - jekyll-gist
    - jemoji
