theme: jekyll-theme-cayman

title: Yiyi's Pages
description: Natural Language Processing, Machine Learning, Deep Learning, Time Series Analysis
url: "https://siebeniris.github.io"
email: yiyi.chen@partner.kit.edu
twitter_username: YiyiChen


# build settings
markdown: kramdown

permalink: /:category/:title

plugins:
    - jekyll-gist
    - jemoji
